M48
; DRILL file {KiCad 9.0.5} date 2025-12-23T10:30:06+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-12-23T10:30:06+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X0.1894Y0.5638
X0.1894Y0.3362
T2
X2.3771Y0.4291
X2.4171Y0.2291
X2.4571Y0.4291
M30
